
CREATE TABLE public.matrizes (
    id bigint NOT NULL,
    identificacao bigint,
    data_nascimento timestamp without time zone,
    proprietarios_id bigint
);
--
-- Name: matrizes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.matrizes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matrizes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nascidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nascidos (
    id bigint NOT NULL,
    identificacao bigint,
    sexo character varying(255),
    data_nascimento timestamp without time zone,
    matrizes_id bigint,
    proprietarios_id bigint
);


--
-- Name: nascidos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nascidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nascidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proprietarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proprietarios (
    id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: proprietarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proprietarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proprietarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reprodutores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reprodutores (
    id bigint NOT NULL,
    identificacao bigint,
    data_nascimento timestamp without time zone,
    proprietarios_id bigint
);


--
-- Name: reprodutores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reprodutores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reprodutores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matrizes matrizes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matrizes
    ADD CONSTRAINT matrizes_pkey PRIMARY KEY (id);


--
-- Name: nascidos nascidos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nascidos
    ADD CONSTRAINT nascidos_pkey PRIMARY KEY (id);


--
-- Name: proprietarios proprietarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proprietarios
    ADD CONSTRAINT proprietarios_pkey PRIMARY KEY (id);


--
-- Name: reprodutores reprodutores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reprodutores
    ADD CONSTRAINT reprodutores_pkey PRIMARY KEY (id);


--
-- Name: nascidos uk5agx0p9gprkejc3yvqixqv1sb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nascidos
    ADD CONSTRAINT uk5agx0p9gprkejc3yvqixqv1sb UNIQUE (identificacao);


--
-- Name: matrizes uko62u7qrik8is5gt3jh587drxt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matrizes
    ADD CONSTRAINT uko62u7qrik8is5gt3jh587drxt UNIQUE (identificacao);


--
-- Name: reprodutores ukrim5n8pi49wvxbori2ifip077; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reprodutores
    ADD CONSTRAINT ukrim5n8pi49wvxbori2ifip077 UNIQUE (identificacao);


--
-- Name: nascidos fkc2phvuxehgrfg139xp01fyxdh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nascidos
    ADD CONSTRAINT fkc2phvuxehgrfg139xp01fyxdh FOREIGN KEY (proprietarios_id) REFERENCES public.proprietarios(id);


--
-- Name: reprodutores fkedk1y0b11ci1vl3o58qq9n6hh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reprodutores
    ADD CONSTRAINT fkedk1y0b11ci1vl3o58qq9n6hh FOREIGN KEY (proprietarios_id) REFERENCES public.proprietarios(id);


--
-- Name: nascidos fkkxvgdm3vij75y6yctkdro8nlp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nascidos
    ADD CONSTRAINT fkkxvgdm3vij75y6yctkdro8nlp FOREIGN KEY (matrizes_id) REFERENCES public.matrizes(id);


--
-- Name: matrizes fkra5265vbb7g87djyu1qy9taih; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matrizes
    ADD CONSTRAINT fkra5265vbb7g87djyu1qy9taih FOREIGN KEY (proprietarios_id) REFERENCES public.proprietarios(id);


--
-- PostgreSQL database dump complete
--

