--
-- PostgreSQL database dump
--

-- Dumped from database version 12.6
-- Dumped by pg_dump version 12.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: bezerras; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bezerras (
    id bigint NOT NULL,
    identificacao bigint,
    data_nascimento timestamp without time zone,
    matrizes_id bigint,
    proprietarios_id bigint
);


--
-- Name: bezerras_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bezerras ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bezerras_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bezerros; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bezerros (
    id bigint NOT NULL,
    identificacao bigint,
    data_nascimento timestamp without time zone,
    matrizes_id bigint,
    proprietarios_id bigint
);


--
-- Name: bezerros_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bezerros ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bezerros_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matrizes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.matrizes (
    id bigint NOT NULL,
    identificacao bigint,
    data_nascimento timestamp without time zone,
    proprietarios_id bigint
);


--
-- Name: matrizes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.matrizes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matrizes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proprietarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proprietarios (
    id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: proprietarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proprietarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proprietarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reprodutores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reprodutores (
    id bigint NOT NULL,
    identificacao bigint,
    data_nascimento timestamp without time zone,
    proprietarios_id bigint
);


--
-- Name: reprodutores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reprodutores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reprodutores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bezerras bezerras_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bezerras
    ADD CONSTRAINT bezerras_pkey PRIMARY KEY (id);


--
-- Name: bezerros bezerros_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bezerros
    ADD CONSTRAINT bezerros_pkey PRIMARY KEY (id);


--
-- Name: matrizes matrizes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matrizes
    ADD CONSTRAINT matrizes_pkey PRIMARY KEY (id);


--
-- Name: proprietarios proprietarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proprietarios
    ADD CONSTRAINT proprietarios_pkey PRIMARY KEY (id);


--
-- Name: reprodutores reprodutores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reprodutores
    ADD CONSTRAINT reprodutores_pkey PRIMARY KEY (id);


--
-- Name: bezerros ukmip0cx8ml0by9bubj7mifgrv3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bezerros
    ADD CONSTRAINT ukmip0cx8ml0by9bubj7mifgrv3 UNIQUE (identificacao);


--
-- Name: matrizes uko62u7qrik8is5gt3jh587drxt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matrizes
    ADD CONSTRAINT uko62u7qrik8is5gt3jh587drxt UNIQUE (identificacao);


--
-- Name: reprodutores ukrim5n8pi49wvxbori2ifip077; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reprodutores
    ADD CONSTRAINT ukrim5n8pi49wvxbori2ifip077 UNIQUE (identificacao);


--
-- Name: bezerras uktjd4j6m4ahfogmuv9264sfop; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bezerras
    ADD CONSTRAINT uktjd4j6m4ahfogmuv9264sfop UNIQUE (identificacao);


--
-- Name: bezerras fk4gf1vjoi4s2c3r0uao3d4hjwo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bezerras
    ADD CONSTRAINT fk4gf1vjoi4s2c3r0uao3d4hjwo FOREIGN KEY (proprietarios_id) REFERENCES public.proprietarios(id);


--
-- Name: bezerros fkbo9dt50i2897kpbgu12qhkrdi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bezerros
    ADD CONSTRAINT fkbo9dt50i2897kpbgu12qhkrdi FOREIGN KEY (proprietarios_id) REFERENCES public.proprietarios(id);


--
-- Name: reprodutores fkedk1y0b11ci1vl3o58qq9n6hh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reprodutores
    ADD CONSTRAINT fkedk1y0b11ci1vl3o58qq9n6hh FOREIGN KEY (proprietarios_id) REFERENCES public.proprietarios(id);


--
-- Name: bezerros fki13qwugqjv12q645bl3retans; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bezerros
    ADD CONSTRAINT fki13qwugqjv12q645bl3retans FOREIGN KEY (matrizes_id) REFERENCES public.matrizes(id);


--
-- Name: bezerras fknuaoqda598eskggbm5rnemxvh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bezerras
    ADD CONSTRAINT fknuaoqda598eskggbm5rnemxvh FOREIGN KEY (matrizes_id) REFERENCES public.matrizes(id);


--
-- Name: matrizes fkra5265vbb7g87djyu1qy9taih; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matrizes
    ADD CONSTRAINT fkra5265vbb7g87djyu1qy9taih FOREIGN KEY (proprietarios_id) REFERENCES public.proprietarios(id);


--
-- PostgreSQL database dump complete
--

